kind: orbiter.caos.ch/Orb
version: v0
clusters:
  k8s:
    kind: orbiter.caos.ch/KubernetesCluster
    version: v0
    spec:
      controlplane:
        nodes: 1
        pool: masters
        provider: kvm
        updatesdisabled: false
      networking:
        dnsdomain: cluster.orbitertest
        network: calico
        podcidr: 100.127.224.0/20
        servicecidr: 100.126.4.0/22
      versions:
        kubernetes: v1.16.0
        orbiter: v0.13.1
        boom: v0.9.11
      workers:
      - nodes: 1
        pool: workers
        provider: kvm
        updatesdisabled: false
providers:
  kvm:
    kind: orbiter.caos.ch/StaticProvider
    version: v0
    spec:
      pools:
        masters:
        - ip: 192.168.122.61
          id: first
          hostname: master01
        workers:
        - ip: 192.168.122.83
          id: second
          hostname: worker01
      remotepublickeypath: /home/orbiter/.ssh/authorized_keys
      remoteuser: orbiter
    loadbalancing:
      kind: orbiter.caos.ch/DynamicLoadBalancer
      version: v0
      spec:
        masters:
        - ip: 192.168.122.0
          transport:
          - name: kubeapi
            sourceport: 6443
            destinations:
            - pool: masters
              port: 6443
              healthchecks:
                code: 200
                path: /healthz
                protocol: https