kind: orbiter.caos.ch/Orb
version: v0
clusters:
  k8s:
    kind: orbiter.caos.ch/KubernetesCluster
    version: v0
    spec:
      controlplane:
        nodes: 1
        pool: masters
        provider: kvm
        updatesdisabled: false
      networking:
        dnsdomain: cluster.orbitertest
        network: calico
        podcidr: 100.127.224.0/20
        servicecidr: 100.126.4.0/22
      versions:
        kubernetes: v1.17.0
        orbiter: v0.15.2
        boom: v0.9.19
      workers:
      - nodes: 1
        pool: workers
        provider: kvm
        updatesdisabled: false
providers:
  kvm:
    kind: orbiter.caos.ch/StaticProvider
    version: v0
    spec:
      pools:
        masters:
        - ip: 192.168.122.61
          id: first
          hostname: master01
        workers:
        - ip: 192.168.122.83
          id: second
          hostname: worker01
      remotepublickeypath: /home/orbiter/.ssh/authorized_keys
      remoteuser: orbiter
    loadbalancing:
      kind: orbiter.caos.ch/DynamicLoadBalancer
      version: v0
      spec:
        masters:
        - ip: 192.168.122.10
          transport:
          - name: kubeapi
            sourceport: 6443
            destinations:
            - pool: masters
              port: 6443
              healthchecks:
                code: 200
                path: /healthz
                protocol: https
<<<<<<< HEAD
=======
        workers:
>>>>>>> kickstart
        - ip: 192.168.122.11
          transport:
          - name: httpsingress
            sourceport: 443
            destinations:
<<<<<<< HEAD
            - pool: workers
              port: 30443
              healthchecks:
                code: 200
                path: /healthz
                protocol: http
          - name: httpingress
            sourceport: 80
            destinations:
            - pool: workers
              port: 30080
              healthchecks:
                code: 200
                path: /healthz
                protocol: https
=======
            - healthchecks:
                protocol: https
                path: /ambassador/v0/check_ready
                code: 200
              port: 30443
              pool: workers
          - name: httpingress
            sourceport: 80
            destinations:
            - healthchecks:
                protocol: http
                path: /ambassador/v0/check_ready
                code: 200
              port: 30080
              pool: workers
>>>>>>> kickstart
