name: "Trigger e2e static provider"
on:
  push:
    branches-ignore:
      - master
#  repository_dispatch:
#    types: webhook-e2e-staticprovider
jobs:
  trigger-e2e-static-provider:
    runs-on: ubuntu-latest
    steps:
#    - name: Cancel Previous Runs
#      uses: styfle/cancel-workflow-action@0.4.1
#      with:
#        access_token: ${{ github.token }}
#    - name: Succeed
#      if: github.event.action == 'webhook-e2e-staticprovider' && github.event.client_payload.status == 'success'
#      run:  exit 0
#    - name: Fail
#      if: github.event.action == 'webhook-e2e-staticprovider' && github.event.client_payload.status == 'failure'
#      run:  exit 1
    - name: Source Checkout
      id: source-checkout
      uses: actions/checkout@v1
    - name: StaticProvider
      run: go run ./cmd/chore/e2e/trigger/*.go --branch "${GITHUB_REF#refs/heads/}" --testcase staticprovider --organization caos --repository ORBOS-Test-StaticProvider --access-token "${{ secrets.E2E_TOKEN }}"
#    - name: Await Response
#      run: sleep 3600
#    - name: Fail
#      run: exit 1
