apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbiter
  namespace: caos-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: orbiter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orbiter
    spec:
      containers:
        - command:
            - /orbctl
            - --orbconfig
            - /etc/orbiter/orbconfig
            - takeoff
            - --recur
            - --deploy=false
            - --ingestion=
          image: eu.gcr.io/caos-240809/orbiter
          env:
            - name: GRPC_GO_LOG_VERBOSITY_LEVEL
              value: "99"
            - name: GRPC_GO_LOG_SEVERITY_LEVEL
              value: info
          ports:
          - name: metrics
            containerPort: 9000
          imagePullPolicy: IfNotPresent
          name: orbiter
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/orbiter
              name: keys
              readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: gcr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      volumes:
        - name: keys
          secret:
            defaultMode: 420
            optional: false
            secretName: caos
